name: Build and deploy

on:
  push:
    branches: ["sly-dump-rebase2"]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Cache Node dependencies
      uses: actions/setup-node@v4
      with:
        cache: pnpm

    - name: Cache Rust workspace
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust

    - name: Install Node dependencies
      run: pnpm install

    - name: Debug
      run: echo "RUST_LOG=info" >> $GITHUB_ENV

    - name: Run build
      run: pnpm run build

    - name: Verify build output
      run: |
        echo "Contents of dist/ directory:"
        ls -la dist/

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact for GitHub Pages
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'
    #   uses: burnett01/rsync-deployments@7.0.2
    #   with:
    #     switches: -va --delete-after --exclude=data/ --exclude=priv/ --exclude=.well-known/
    #     path: dist/
    #     remote_path: noclip.website/
    #     remote_host: iad1-shared-e1-29.dreamhost.com
    #     remote_user: gznoclip
    #     remote_key: ${{ secrets.DEPLOY_KEY }}
